import { Link } from "react-router-dom";
import { APPLICATION_STATUSES, useApplications } from "./ApplicationsContext";

export default function Applications() {
  const { applications, removeApplication, updateApplication, toggleChecklist } = useApplications();
  const today = new Date();
  const daysUntil = (date) => { if (!date) return null; return Math.ceil((new Date(`${date}T23:59:59`) - today) / 86400000); };
  const pending = applications.filter((a) => a.status !== "Decision received").length;
  const applied = applications.filter((a) => a.status === "Applied").length;
  const dueSoon = applications.filter((a) => { const d = daysUntil(a.deadline); return d !== null && d >= 0 && d <= 14; }).length;
  return <div className="p-4 md:p-6 max-w-6xl mx-auto space-y-6">
    <div className="flex flex-wrap justify-between gap-4 items-end"><div><h1 className="text-3xl font-bold text-indigo-velvet">Application tracker</h1><p className="text-sm text-medium-slate-blue/70 mt-1">Keep deadlines, documents and next steps in one place.</p></div><Link to="/search" className="btn bg-medium-slate-blue text-white hover:bg-amber-flame border-0">Add university</Link></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[["Applications", applications.length], ["In progress", pending], ["Applied", applied], ["Due in 14 days", dueSoon]].map(([label, value]) => <div key={label} className="card bg-base-100 border border-medium-slate-blue/15 shadow-sm"><div className="card-body p-4"><div className="text-xs uppercase tracking-wide text-medium-slate-blue/60">{label}</div><div className="text-2xl font-bold text-indigo-velvet">{value}</div></div></div>)}</div>
    {!applications.length ? <div className="card bg-base-100 border border-dashed border-medium-slate-blue/30"><div className="card-body text-center py-16"><div className="text-5xl mb-3">🎓</div><h2 className="text-xl font-semibold">No applications yet</h2><p className="text-sm text-medium-slate-blue/70 max-w-md mx-auto">Search for a university and add it to your application tracker. Then set its deadline and work through the checklist.</p><Link to="/search" className="btn btn-outline mt-4">Find a university</Link></div></div> : <div className="space-y-4">{applications.map((app) => { const completed = app.checklist.filter((x) => x.done).length; const days = daysUntil(app.deadline); return <article key={app.id} className="card bg-base-100 border border-medium-slate-blue/15 shadow-sm"><div className="card-body p-4 md:p-5">
      <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div className="min-w-0"><h2 className="text-xl font-bold text-indigo-velvet">{app.name}</h2><p className="text-sm text-medium-slate-blue/70">{app.country}{app["state-province"] ? ` · ${app["state-province"]}` : ""}</p>{app.web_pages?.[0] && <a href={app.web_pages[0]} target="_blank" rel="noopener noreferrer" className="link text-sm text-medium-slate-blue hover:text-tiger-orange">Official university website ↗</a>}</div><div className="flex flex-wrap gap-2 items-center"><select className="select select-sm" value={app.status} onChange={(e) => updateApplication(app.id, { status: e.target.value })}>{APPLICATION_STATUSES.map((s) => <option key={s}>{s}</option>)}</select><button className="btn btn-sm btn-ghost text-error" onClick={() => removeApplication(app.id)}>Remove</button></div></div>
      <div className="grid md:grid-cols-[220px_1fr] gap-5 mt-4"><div className="space-y-3"><label className="form-control"><span className="label-text text-xs font-semibold">Application deadline</span><input type="date" className="input input-bordered input-sm" value={app.deadline} onChange={(e) => updateApplication(app.id, { deadline: e.target.value })}/></label>{days !== null && <div className={`text-sm font-medium ${days <= 14 ? "text-error" : "text-medium-slate-blue"}`}>{days < 0 ? `${Math.abs(days)} days overdue` : days === 0 ? "Deadline is today" : `${days} days remaining`}</div>}<label className="form-control"><span className="label-text text-xs font-semibold">Private notes</span><textarea className="textarea textarea-bordered textarea-sm" rows="3" placeholder="Requirements, portal link, questions..." value={app.note} onChange={(e) => updateApplication(app.id, { note: e.target.value })}/></label></div>
      <div><div className="flex justify-between items-center mb-2"><h3 className="font-semibold">Application checklist</h3><span className="text-xs text-medium-slate-blue/60">{completed}/{app.checklist.length} complete</span></div><progress className="progress progress-warning w-full mb-3" value={completed} max={app.checklist.length}/><div className="space-y-2">{app.checklist.map((task) => <label key={task.id} className="flex gap-3 items-center p-2 rounded-lg hover:bg-base-200 cursor-pointer"><input type="checkbox" className="checkbox checkbox-sm" checked={task.done} onChange={() => toggleChecklist(app.id, task.id)}/><span className={task.done ? "line-through opacity-50" : ""}>{task.label}</span></label>)}</div></div></div>
    </div></article>; })}</div>}
  </div>;
}
