import { Link } from "react-router-dom";

export default function Home() {
  return <div className="max-w-6xl mx-auto p-6 md:p-10 space-y-12">
    <section className="grid lg:grid-cols-[1.3fr_.7fr] gap-8 items-center pt-8">
      <div><span className="badge bg-amber-flame text-indigo-velvet border-0 mb-4">University application workspace</span><h1 className="text-4xl md:text-6xl font-bold leading-tight text-indigo-velvet">Find universities and actually move your applications forward.</h1><p className="mt-5 text-lg text-medium-slate-blue/75 max-w-2xl">UniSearch turns university discovery into a practical workflow: find a university, add it to your application tracker, set the deadline, and work through the tasks before you submit.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/search" className="btn bg-medium-slate-blue text-white hover:bg-amber-flame border-0">Find universities</Link><Link to="/applications" className="btn btn-outline">Open application tracker</Link></div></div>
      <div className="card bg-indigo-velvet text-white shadow-xl"><div className="card-body p-6"><div className="text-sm text-white/60">Your workflow</div>{[["01", "Discover", "Search by university or country"],["02", "Plan", "Set deadlines and notes"],["03", "Prepare", "Complete the application checklist"],["04", "Submit", "Track your application status"]].map(([n, title, text]) => <div key={n} className="flex gap-4 py-4 border-b border-white/10 last:border-0"><span className="text-amber-flame font-bold">{n}</span><div><div className="font-semibold">{title}</div><div className="text-sm text-white/60">{text}</div></div></div>)}</div></div>
    </section>
    <section className="grid md:grid-cols-3 gap-5">{[["🔎", "University discovery", "Search the university directory by name, country, or both and open the official university website."],["📅", "Deadline tracking", "Record each application deadline and see when an application is approaching or overdue."],["✅", "Application checklist", "Track requirements, documents, statement preparation, and submission for each university."]].map(([icon, title, text]) => <div key={title} className="card bg-base-100 border border-medium-slate-blue/15 shadow-sm"><div className="card-body"><div className="text-3xl">{icon}</div><h2 className="card-title text-indigo-velvet">{title}</h2><p className="text-sm text-medium-slate-blue/70">{text}</p></div></div>)}</section>
    <section className="card bg-base-200"><div className="card-body md:flex-row items-center justify-between gap-5"><div><h2 className="text-2xl font-bold text-indigo-velvet">Start with one university.</h2><p className="text-sm text-medium-slate-blue/70">Build your application pipeline as you discover more.</p></div><Link to="/search" className="btn bg-amber-flame text-indigo-velvet border-0 hover:bg-tiger-orange">Start searching</Link></div></section>
  </div>;
}
