import { Link } from "react-router-dom";

export default function Home() {
  return <div className="max-w-6xl mx-auto p-6 md:p-10 space-y-12">
    <section className="grid lg:grid-cols-[1.3fr_.7fr] gap-8 items-center pt-8">
      <div><span className="badge bg-amber-flame text-indigo-velvet border-0 mb-4">University discovery</span><h1 className="text-4xl md:text-6xl font-bold leading-tight text-indigo-velvet">Find the right university for your next step.</h1><p className="mt-5 text-lg text-medium-slate-blue/75 max-w-2xl">UniSearch helps you discover universities by name or country, refine your results, and open official university websites directly.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/search" className="btn bg-medium-slate-blue text-white hover:bg-amber-flame border-0">Find universities</Link></div></div>
      <div className="card bg-indigo-velvet text-white shadow-xl"><div className="card-body p-6"><div className="text-sm text-white/60">How it works</div>{[["01", "Search", "Enter a university name or choose a country"],["02", "Refine", "Filter and sort the universities you find"],["03", "Explore", "Open the official university website"]].map(([n, title, text]) => <div key={n} className="flex gap-4 py-4 border-b border-white/10 last:border-0"><span className="text-amber-flame font-bold">{n}</span><div><div className="font-semibold">{title}</div><div className="text-sm text-white/60">{text}</div></div></div>)}</div></div>
    </section>
    <section className="grid md:grid-cols-3 gap-5">{[["🔎", "Search by name", "Find universities using a university name without requiring an exact match."],["🌍", "Filter by country", "Use the optional country dropdown to narrow your university search."],["🔗", "Official websites", "Open the official university website directly from the results."]].map(([icon, title, text]) => <div key={title} className="card bg-base-100 border border-medium-slate-blue/15 shadow-sm"><div className="card-body"><div className="text-3xl">{icon}</div><h2 className="card-title text-indigo-velvet">{title}</h2><p className="text-sm text-medium-slate-blue/70">{text}</p></div></div>)}</section>
    <section className="card bg-base-200"><div className="card-body md:flex-row items-center justify-between gap-5"><div><h2 className="text-2xl font-bold text-indigo-velvet">Start exploring universities.</h2><p className="text-sm text-medium-slate-blue/70">Search by university name, country, or both.</p></div><Link to="/search" className="btn bg-amber-flame text-indigo-velvet border-0 hover:bg-tiger-orange">Start searching</Link></div></section>
  </div>;
}
